import StyledComponentsRegistry from "@/lib/registry";
import type { Metadata } from "next";
import localFont from "next/font/local";
import GlobalStyle from "./styles/globalStyles";
import ThemeWrapper from "./styles/themeWrapper";
import NavbarItem from "./components/navbar/navbarItem";
import { Container } from "./styles/style";
import FooterItem from "./components/footer/footerItem";
import ContextWrapper from "./contextWrapper";
import { PopupProvider } from "@/contexts/popupContext";
import { CityProvider } from "@/contexts/cityContext";

const PtRootUiVf = localFont({
  src: "./pt-root-ui_vf.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Окошко",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={PtRootUiVf.className}>
        <StyledComponentsRegistry>
          <GlobalStyle />
          <ThemeWrapper>
            <ContextWrapper>
              <PopupProvider>
                <CityProvider>
                  <NavbarItem />
                  <Container>{children}</Container>
                  <FooterItem />
                </CityProvider>
              </PopupProvider>
            </ContextWrapper>
          </ThemeWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
